apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
spec:
  releaseName: reflector
  chart:
    spec:
      chart: reflector
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      version: "6.1.47"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3