apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - jetstack.yaml
  - emberstack.yaml
  - sealedsecrets.yaml
  - bitnami.yaml
  - bitnami-full-index.yaml
  - podinfo.yaml
  - uptime-kuma.yaml