apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: uptime-kuma-monitor
  labels:
    app: uptime-kuma
    release: prometheus-stack
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: http
  namespaceSelector:
    matchNames:
      - infra
  selector:
    matchLabels:      
      app.kubernetes.io/name: uptime-kuma