apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma  
spec:
  releaseName: uptime-kuma
  targetNamespace: infra
  chart:
    spec:
      chart: uptime-kuma
      version: "2.4.1"
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: flux-system
  interval: 10m  
  values:
    podLabels: 
      app: uptime-kuma
    resources:
      limits:
        #cpu: 100m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi