apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: flux-system
  name: sealed-secrets
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
      version: 2.1.6
  interval: 1h0m0s
  install:
    crds: Skip
  valuesFrom:
    - kind: ConfigMap
      name: sealedsecrets-values